# Прогнозирование оттока клиентов в сети отелей «Как в гостях»

### Шаг 1. Откройте файлы с данными

In [1012]:
import pandas as pd

df_test = pd.read_csv('hotel_test.csv')
df_train = pd.read_csv('hotel_train.csv')

In [1013]:
df_test

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights
0,6086,1,74.0,2017,January,1,1,1,0,2.0,...,0,0,0,A,0,0,Transient,0,0,1
1,6087,1,62.0,2017,January,1,1,2,2,2.0,...,0,0,0,A,0,0,Transient,0,1,4
2,6088,1,62.0,2017,January,1,1,2,2,2.0,...,0,0,0,A,0,0,Transient,0,1,4
3,6089,1,71.0,2017,January,1,1,2,2,1.0,...,0,0,0,A,0,0,Transient,0,1,4
4,6090,1,172.0,2017,January,1,1,2,5,2.0,...,0,0,0,A,0,0,Transient,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32407,97899,0,164.0,2017,August,35,31,2,4,2.0,...,0,0,0,A,0,0,Transient,0,0,6
32408,97900,0,21.0,2017,August,35,30,2,5,2.0,...,0,0,0,A,0,0,Transient,0,2,7
32409,97901,0,23.0,2017,August,35,30,2,5,2.0,...,0,0,0,A,0,0,Transient,0,0,7
32410,97902,0,34.0,2017,August,35,31,2,5,2.0,...,0,0,0,D,0,0,Transient,0,4,7
32411,97903,0,109.0,2017,August,35,31,2,5,2.0,...,0,0,0,A,0,0,Transient,0,0,7

In [1016]:
df_train

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights
0,0,0,7.0,2015,July,27,1,0,1,1.0,...,0,0,0,A,0,0,Transient,0,0,1
1,1,0,14.0,2015,July,27,1,0,2,2.0,...,0,0,0,A,0,0,Transient,0,1,2
2,2,0,0.0,2015,July,27,1,0,2,2.0,...,0,0,0,C,0,0,Transient,0,0,2
3,3,0,9.0,2015,July,27,1,0,2,2.0,...,0,0,0,C,0,0,Transient,0,1,2
4,4,1,85.0,2015,July,27,1,0,3,2.0,...,0,0,0,A,0,0,Transient,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65224,84057,0,23.0,2016,December,53,30,2,4,2.0,...,0,0,0,D,0,0,Transient,0,2,6
65225,84063,0,53.0,2016,December,53,31,2,3,2.0,...,0,0,0,D,0,0,Transient,0,3,5
65226,84094,0,7.0,2016,December,53,31,2,4,2.0,...,0,0,0,D,0,0,Transient,0,1,6
65227,84117,0,17.0,2016,December,53,30,2,5,2.0,...,0,0,0,A,0,0,Transient,0,1,7
65228,84121,0,107.0,2016,December,53,31,2,5,2.0,...,0,0,0,A,0,0,Transient,0,0,7

### Шаг 2. Предобработка и исследовательский анализ данных

In [1019]:
df_train.shape

(65229, 25)

In [1021]:
df_test = df_test.astype(
    {
        'id':'str'
    }
)
df_train = df_train.astype(
    {
        'id':'str'
    }
)

In [1023]:
df_train.duplicated().sum()

0

In [1025]:
df_test.duplicated().sum()

0

In [1027]:
df_train.boxplot('lead_time')  
df_train.hist('lead_time')

array([[<Axes: title={'center': 'lead_time'}>]], dtype=object)

In [1029]:
df_train.boxplot('lead_time')  
df_train.hist('lead_time')

array([[<Axes: title={'center': 'lead_time'}>]], dtype=object)

In [1031]:
df_test.arrival_date_month.unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August'], dtype=object)

In [1033]:
df_train.boxplot('adults')

In [1035]:
df_train.query('adults == 0')

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights
17540,25480,0,1.0,2015,August,33,10,1,1,0.0,...,0,0,0,B,1,0,Transient-Party,0,0,2
17598,25538,0,104.0,2015,August,33,11,0,3,0.0,...,0,0,0,B,1,0,Transient-Party,0,2,3
17982,25922,0,3.0,2015,August,34,16,2,0,0.0,...,0,0,0,B,1,0,Transient-Party,0,1,2
21556,29496,1,48.0,2015,October,43,19,1,3,0.0,...,0,0,0,B,0,0,Transient-Party,0,1,4
22516,30456,1,6.0,2015,December,51,13,1,0,0.0,...,0,0,0,B,0,0,Transient-Party,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64751,83478,0,197.0,2016,December,52,21,1,4,0.0,...,0,0,0,A,7,0,Transient-Party,0,0,5
64882,83610,0,104.0,2016,December,53,25,2,1,0.0,...,0,0,0,B,1,0,Transient,0,2,3
64892,83620,0,104.0,2016,December,53,25,2,1,0.0,...,0,0,0,B,0,0,Transient,0,2,3
64903,83633,0,247.0,2016,December,52,24,2,3,0.0,...,0,0,0,B,0,0,Transient,0,1,5
64980,83710,0,255.0,2016,December,53,27,0,3,0.0,...,0,0,0,A,3,0,Transient,0,0,3

возможно нужно удалить заказы без детей и взрослых

In [1038]:
df_train.shape

(65229, 25)

In [1040]:
print(df_train.query('adults == 0 and children == 0').shape)
df_train = df_train.drop(df_train.query('adults == 0').index)
df_train

(15, 25)

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights
0,0,0,7.0,2015,July,27,1,0,1,1.0,...,0,0,0,A,0,0,Transient,0,0,1
1,1,0,14.0,2015,July,27,1,0,2,2.0,...,0,0,0,A,0,0,Transient,0,1,2
2,2,0,0.0,2015,July,27,1,0,2,2.0,...,0,0,0,C,0,0,Transient,0,0,2
3,3,0,9.0,2015,July,27,1,0,2,2.0,...,0,0,0,C,0,0,Transient,0,1,2
4,4,1,85.0,2015,July,27,1,0,3,2.0,...,0,0,0,A,0,0,Transient,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65224,84057,0,23.0,2016,December,53,30,2,4,2.0,...,0,0,0,D,0,0,Transient,0,2,6
65225,84063,0,53.0,2016,December,53,31,2,3,2.0,...,0,0,0,D,0,0,Transient,0,3,5
65226,84094,0,7.0,2016,December,53,31,2,4,2.0,...,0,0,0,D,0,0,Transient,0,1,6
65227,84117,0,17.0,2016,December,53,30,2,5,2.0,...,0,0,0,A,0,0,Transient,0,1,7
65228,84121,0,107.0,2016,December,53,31,2,5,2.0,...,0,0,0,A,0,0,Transient,0,0,7

In [1042]:
df_train.shape

(65063, 25)

In [1044]:
df_test = df_test.drop(df_test.query('adults == 0').index)

In [1046]:
df_train.boxplot('total_nights')

### Шаг 3. Формулировка ML-задачи на основе бизнес-задачи

добавим столбец и объединим данные

In [1051]:
df_train['is_test'] = df_train.apply(lambda x: 0, axis=1)
df_test['is_test'] = df_test.apply(lambda x: 1, axis=1)

In [1052]:
df = pd.concat([df_train, df_test])
df.shape

(97406, 26)

сделаем месяца цифрами

In [1056]:
df.arrival_date_month.unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

добавим колонки с ценами за ночь и обслуживания с учетом сезона

In [1059]:
def season(x):
    if x in ['January', 'February', 'December']:
        return 1
    if x in ['March', 'April', 'May']:
        return 1.2
    if x in ['June', 'July', 'August']:
        return 1.4
    return 1.2

In [1061]:
df['coef'] = df.arrival_date_month.apply(lambda x: season(x))
df

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights,is_test,coef
0,0,0,7.0,2015,July,27,1,0,1,1.0,...,0,A,0,0,Transient,0,0,1,0,1.4
1,1,0,14.0,2015,July,27,1,0,2,2.0,...,0,A,0,0,Transient,0,1,2,0,1.4
2,2,0,0.0,2015,July,27,1,0,2,2.0,...,0,C,0,0,Transient,0,0,2,0,1.4
3,3,0,9.0,2015,July,27,1,0,2,2.0,...,0,C,0,0,Transient,0,1,2,0,1.4
4,4,1,85.0,2015,July,27,1,0,3,2.0,...,0,A,0,0,Transient,0,1,3,0,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32407,97899,0,164.0,2017,August,35,31,2,4,2.0,...,0,A,0,0,Transient,0,0,6,1,1.4
32408,97900,0,21.0,2017,August,35,30,2,5,2.0,...,0,A,0,0,Transient,0,2,7,1,1.4
32409,97901,0,23.0,2017,August,35,30,2,5,2.0,...,0,A,0,0,Transient,0,0,7,1,1.4
32410,97902,0,34.0,2017,August,35,31,2,5,2.0,...,0,D,0,0,Transient,0,4,7,1,1.4
32411,97903,0,109.0,2017,August,35,31,2,5,2.0,...,0,A,0,0,Transient,0,0,7,1,1.4

In [1063]:
df.reserved_room_type.unique()

array(['A               ', 'C               ', 'D               ',
       'E               ', 'G               ', 'F               ',
       'B               '], dtype=object)

In [1065]:
df.reserved_room_type = df.reserved_room_type.replace(
    {
        'A               ':'A', 
        'B               ':'B', 
        'C               ':'C', 
        'D               ':'D', 
        'E               ':'E', 
        'F               ':'F', 
        'G               ':'G'
    }
)

In [1067]:
df.reserved_room_type.unique()

array(['A', 'C', 'D', 'E', 'G', 'F', 'B'], dtype=object)

In [1069]:
df.meal = df.meal.apply(lambda x: x.split()[0])

In [1071]:
df.meal.unique()

array(['BB', 'FB', 'HB', 'SC'], dtype=object)

прибыль без депозита

In [1074]:
def profit(x):
    if(x['is_canceled'] == 0):
        if(x['reserved_room_type'] == 'A'):
            return (x['total_nights'] * 1000 * x['coef']) - ((x['total_nights'] // 2 + 1) * 400 * x['coef'])
        if(x['reserved_room_type'] == 'B'):
            return (x['total_nights'] * 800 * x['coef']) - ((x['total_nights'] // 2 + 1) * 350 * x['coef'])
        if(x['reserved_room_type'] == 'C'):
            return (x['total_nights'] * 600 * x['coef']) - ((x['total_nights'] // 2 + 1) * 350 * x['coef'])
        if(x['reserved_room_type'] == 'D'):
            return (x['total_nights'] * 550 * x['coef']) - ((x['total_nights'] // 2 + 1) * 150 * x['coef'])
        if(x['reserved_room_type'] == 'E'):
            return (x['total_nights'] * 500 * x['coef']) - ((x['total_nights'] // 2 + 1) * 150 * x['coef'])
        if(x['reserved_room_type'] == 'F'):
            return (x['total_nights'] * 450 * x['coef']) - ((x['total_nights'] // 2 + 1) * 150 * x['coef'])
        if(x['reserved_room_type'] == 'G'):
            return (x['total_nights'] * 350 * x['coef']) - ((x['total_nights'] // 2 + 1) * 150 * x['coef'])
    else:
        if(x['reserved_room_type'] == 'A'):
            return -((1000 + 400) * x['coef'])
        if(x['reserved_room_type'] == 'B'):
            return -((800 + 350) * x['coef'])
        if(x['reserved_room_type'] == 'C'):
            return -((600 + 350) * x['coef'])
        if(x['reserved_room_type'] == 'D'):
            return -((550 + 150) * x['coef'])
        if(x['reserved_room_type'] == 'E'):
            return -((500 + 150) * x['coef'])
        if(x['reserved_room_type'] == 'F'):
            return -((450 + 150) * x['coef'])
        if(x['reserved_room_type'] == 'G'):
            return -((350 + 150) * x['coef'])

In [1076]:
df['profit_one_order'] = df.apply(profit, axis=1)

In [1077]:
df[df['is_test'] == 1].shape

(32343, 28)

In [1078]:
df_test.shape

(32343, 26)

In [1079]:
df_test.reserved_room_type = df_test.reserved_room_type.replace(
    {
        'A               ':'A', 
        'B               ':'B', 
        'C               ':'C', 
        'D               ':'D', 
        'E               ':'E', 
        'F               ':'F', 
        'G               ':'G'
    }
)
df_test['coef'] = df_test.arrival_date_month.apply(lambda x: season(x))
df_test['profit_one_order'] = df_test.apply(profit, axis=1)
df_test['profit_one_order'].sum()

28196210.0

In [1080]:
income_without_deposite = df.query('is_test == 1')['profit_one_order'].sum()
income_without_deposite

28196210.0

### Шаг 4. Разработка модели ML

In [1082]:
df_train

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights,is_test
0,0,0,7.0,2015,July,27,1,0,1,1.0,...,0,0,A,0,0,Transient,0,0,1,0
1,1,0,14.0,2015,July,27,1,0,2,2.0,...,0,0,A,0,0,Transient,0,1,2,0
2,2,0,0.0,2015,July,27,1,0,2,2.0,...,0,0,C,0,0,Transient,0,0,2,0
3,3,0,9.0,2015,July,27,1,0,2,2.0,...,0,0,C,0,0,Transient,0,1,2,0
4,4,1,85.0,2015,July,27,1,0,3,2.0,...,0,0,A,0,0,Transient,0,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65224,84057,0,23.0,2016,December,53,30,2,4,2.0,...,0,0,D,0,0,Transient,0,2,6,0
65225,84063,0,53.0,2016,December,53,31,2,3,2.0,...,0,0,D,0,0,Transient,0,3,5,0
65226,84094,0,7.0,2016,December,53,31,2,4,2.0,...,0,0,D,0,0,Transient,0,1,6,0
65227,84117,0,17.0,2016,December,53,30,2,5,2.0,...,0,0,A,0,0,Transient,0,1,7,0
65228,84121,0,107.0,2016,December,53,31,2,5,2.0,...,0,0,A,0,0,Transient,0,0,7,0

In [1083]:
df_train.meal = df_train.meal.apply(lambda x: x.split()[0])
df_train.meal.unique()

array(['BB', 'FB', 'HB', 'SC'], dtype=object)

In [1087]:
def month_y(x):
    if x == 'January':
        return 1
    if x == 'February':
        return 2
    if x == 'March':
        return 3
    if x == 'April':
        return 4
    if x == 'May':
        return 5
    if x == 'June':
        return 6
    if x == 'July':
        return 7
    if x == 'August':
        return 8
    if x == 'September':
        return 9
    if x == 'October':
        return 10
    if x == 'November':
        return 11
    return 12

In [1088]:
df.arrival_date_month = df.arrival_date_month.apply(month_y)

In [1091]:
df

,id,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights,is_test,coef,profit_one_order
0,0,0,7.0,2015,7,27,1,0,1,1.0,...,A,0,0,Transient,0,0,1,0,1.4,840.0
1,1,0,14.0,2015,7,27,1,0,2,2.0,...,A,0,0,Transient,0,1,2,0,1.4,1680.0
2,2,0,0.0,2015,7,27,1,0,2,2.0,...,C,0,0,Transient,0,0,2,0,1.4,700.0
3,3,0,9.0,2015,7,27,1,0,2,2.0,...,C,0,0,Transient,0,1,2,0,1.4,700.0
4,4,1,85.0,2015,7,27,1,0,3,2.0,...,A,0,0,Transient,0,1,3,0,1.4,-1960.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32407,97899,0,164.0,2017,8,35,31,2,4,2.0,...,A,0,0,Transient,0,0,6,1,1.4,6160.0
32408,97900,0,21.0,2017,8,35,30,2,5,2.0,...,A,0,0,Transient,0,2,7,1,1.4,7560.0
32409,97901,0,23.0,2017,8,35,30,2,5,2.0,...,A,0,0,Transient,0,0,7,1,1.4,7560.0
32410,97902,0,34.0,2017,8,35,31,2,5,2.0,...,D,0,0,Transient,0,4,7,1,1.4,4550.0
32411,97903,0,109.0,2017,8,35,31,2,5,2.0,...,A,0,0,Transient,0,0,7,1,1.4,7560.0

In [1094]:
df = df.drop('id', axis=1)

In [1097]:
df

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,reserved_room_type,booking_changes,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests,total_nights,is_test,coef,profit_one_order
0,0,7.0,2015,7,27,1,0,1,1.0,0.0,...,A,0,0,Transient,0,0,1,0,1.4,840.0
1,0,14.0,2015,7,27,1,0,2,2.0,0.0,...,A,0,0,Transient,0,1,2,0,1.4,1680.0
2,0,0.0,2015,7,27,1,0,2,2.0,0.0,...,C,0,0,Transient,0,0,2,0,1.4,700.0
3,0,9.0,2015,7,27,1,0,2,2.0,0.0,...,C,0,0,Transient,0,1,2,0,1.4,700.0
4,1,85.0,2015,7,27,1,0,3,2.0,0.0,...,A,0,0,Transient,0,1,3,0,1.4,-1960.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32407,0,164.0,2017,8,35,31,2,4,2.0,0.0,...,A,0,0,Transient,0,0,6,1,1.4,6160.0
32408,0,21.0,2017,8,35,30,2,5,2.0,0.0,...,A,0,0,Transient,0,2,7,1,1.4,7560.0
32409,0,23.0,2017,8,35,30,2,5,2.0,0.0,...,A,0,0,Transient,0,0,7,1,1.4,7560.0
32410,0,34.0,2017,8,35,31,2,5,2.0,0.0,...,D,0,0,Transient,0,4,7,1,1.4,4550.0
32411,0,109.0,2017,8,35,31,2,5,2.0,0.0,...,A,0,0,Transient,0,0,7,1,1.4,7560.0

In [1100]:
df = pd.get_dummies(df, drop_first=True)
df

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,distribution_channel_TA/TO,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,7.0,2015,7,27,1,0,1,1.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,0,14.0,2015,7,27,1,0,2,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
2,0,0.0,2015,7,27,1,0,2,2.0,0.0,...,False,False,True,False,False,False,False,False,True,False
3,0,9.0,2015,7,27,1,0,2,2.0,0.0,...,False,False,True,False,False,False,False,False,True,False
4,1,85.0,2015,7,27,1,0,3,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32407,0,164.0,2017,8,35,31,2,4,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
32408,0,21.0,2017,8,35,30,2,5,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
32409,0,23.0,2017,8,35,30,2,5,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
32410,0,34.0,2017,8,35,31,2,5,2.0,0.0,...,True,False,False,True,False,False,False,False,True,False
32411,0,109.0,2017,8,35,31,2,5,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False

In [1101]:
df_train = df.query('is_test == 0')
df_test = df.query('is_test == 1')
df_test.profit_one_order

0       -1400.0
1       -1400.0
2       -1400.0
3       -1400.0
4       -1400.0
          ...
32407    6160.0
32408    7560.0
32409    7560.0
32410    4550.0
32411    7560.0
Name: profit_one_order, Length: 32343, dtype: float64

In [1104]:
features = df_train.drop(['is_canceled', 'coef', 'profit_one_order'], axis=1)
target = df_train['is_canceled']

features_test = df_test.drop(['is_canceled', 'coef', 'profit_one_order'], axis=1)
target_test = df_test['is_canceled']

In [1107]:
df_train

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,distribution_channel_TA/TO,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,7.0,2015,7,27,1,0,1,1.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,0,14.0,2015,7,27,1,0,2,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
2,0,0.0,2015,7,27,1,0,2,2.0,0.0,...,False,False,True,False,False,False,False,False,True,False
3,0,9.0,2015,7,27,1,0,2,2.0,0.0,...,False,False,True,False,False,False,False,False,True,False
4,1,85.0,2015,7,27,1,0,3,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65224,0,23.0,2016,12,53,30,2,4,2.0,0.0,...,True,False,False,True,False,False,False,False,True,False
65225,0,53.0,2016,12,53,31,2,3,2.0,0.0,...,True,False,False,True,False,False,False,False,True,False
65226,0,7.0,2016,12,53,31,2,4,2.0,0.0,...,True,False,False,True,False,False,False,False,True,False
65227,0,17.0,2016,12,53,30,2,5,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False
65228,0,107.0,2016,12,53,31,2,5,2.0,0.0,...,True,False,False,False,False,False,False,False,True,False

In [1109]:
features

,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,distribution_channel_TA/TO,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,7.0,2015,7,27,1,0,1,1.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False
1,14.0,2015,7,27,1,0,2,2.0,0.0,0.0,...,True,False,False,False,False,False,False,False,True,False
2,0.0,2015,7,27,1,0,2,2.0,0.0,0.0,...,False,False,True,False,False,False,False,False,True,False
3,9.0,2015,7,27,1,0,2,2.0,0.0,0.0,...,False,False,True,False,False,False,False,False,True,False
4,85.0,2015,7,27,1,0,3,2.0,0.0,0.0,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65224,23.0,2016,12,53,30,2,4,2.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
65225,53.0,2016,12,53,31,2,3,2.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
65226,7.0,2016,12,53,31,2,4,2.0,0.0,0.0,...,True,False,False,True,False,False,False,False,True,False
65227,17.0,2016,12,53,30,2,5,2.0,0.0,0.0,...,True,False,False,False,False,False,False,False,True,False
65228,107.0,2016,12,53,31,2,5,2.0,0.0,0.0,...,True,False,False,False,False,False,False,False,True,False

In [1111]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(features)
features = pd.DataFrame(data=scaler.transform(features), columns=features.columns)

features

,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,distribution_channel_TA/TO,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,-0.928960,-1.597637,-0.145651,-0.322666,-1.696881,-0.966529,-0.903325,-1.783099,-0.219332,-0.073045,...,-2.247498,-0.105336,-0.059301,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
1,-0.856175,-1.597637,-0.145651,-0.322666,-1.696881,-0.966529,-0.165471,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
2,-1.001744,-1.597637,-0.145651,-0.322666,-1.696881,-0.966529,-0.165471,0.336455,-0.219332,-0.073045,...,-2.247498,-0.105336,16.863097,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
3,-0.908164,-1.597637,-0.145651,-0.322666,-1.696881,-0.966529,-0.165471,0.336455,-0.219332,-0.073045,...,-2.247498,-0.105336,16.863097,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
4,-0.117932,-1.597637,-0.145651,-0.322666,-1.696881,-0.966529,0.572384,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65058,-0.762595,0.625924,1.468079,1.608945,1.618089,1.377226,1.310238,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,2.435705,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
65059,-0.450661,0.625924,1.468079,1.608945,1.732399,1.377226,0.572384,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,2.435705,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
65060,-0.928960,0.625924,1.468079,1.608945,1.732399,1.377226,1.310238,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,2.435705,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
65061,-0.824982,0.625924,1.468079,1.608945,1.618089,1.377226,2.048092,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597
65062,0.110819,0.625924,1.468079,1.608945,1.732399,1.377226,2.048092,0.336455,-0.219332,-0.073045,...,0.444939,-0.105336,-0.059301,-0.410559,-0.197601,-0.137716,-0.095825,-0.066447,0.65806,-0.58597

In [120]:
# дерево решений
%matplotlib


from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

rez = []
best_rez = 0
best_model = None
dep = 0

for d in range(1, 20):
    model = DecisionTreeClassifier(random_state=12345, max_depth=d, class_weight='balanced')
    roc = cross_val_score(model, features, target, cv=8, scoring='roc_auc').mean()
    rez.append(roc)
    if(roc > best_rez):
        best_rez = roc
        best_model = model
        dep = d

print(best_rez, dep)
    
pd.DataFrame(rez, [i for i in range(1, 20)]).plot()

Using matplotlib backend: <object object at 0x0000012F02491900>

KeyboardInterrupt:

In [ ]:
# случайный лес
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

parameters={ # задаем параметры
    'n_estimators': [80, 248, 540], 
    'max_depth': [2, 8, 16],
    'max_features': [3, 4, 5]
}
model = RandomForestClassifier(random_state=12345, class_weight='balanced')
clf_model = GridSearchCV(model, parameters, scoring= 'roc_auc', cv=8, n_jobs=-1)

clf_model.fit(features, target)

print(clf_model.best_params_, clf_model.best_score_)

In [754]:
# случайный лес
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

parameters={ # задаем параметры
    'n_estimators': [50], 
    'max_depth': [1],
    'max_features': [4, 5, 6, 7, 8]
}
model = RandomForestClassifier(random_state=12345, class_weight='balanced')
clf_model = GridSearchCV(model, parameters, scoring= 'roc_auc', cv=8, n_jobs=-1)

clf_model.fit(features, target)

print(clf_model.best_params_, clf_model.best_score_)

{'max_depth': 1, 'max_features': 4, 'n_estimators': 50} 0.7623681690747413

In [1113]:
features.shape

(65063, 207)

In [1115]:
target.shape

(65063,)

In [1117]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

model = LogisticRegression(random_state=12345, class_weight='balanced', solver='lbfgs', max_iter=1000)
cvs_model = cross_val_score(model, features, target, cv=8, scoring='roc_auc')
print(cvs_model.mean())

0.8185079463067432

In [1118]:
features.shape

(65063, 207)

In [1119]:
target.shape

(65063,)

In [1120]:
from sklearn.metrics import f1_score
import numpy as np
from sklearn.model_selection import train_test_split

features_train, features_valid, target_train, target_valid = train_test_split( 
features, target, test_size=0.25, random_state=12345, shuffle=True, stratify=target)
model = LogisticRegression(random_state=12345, class_weight='balanced', solver='lbfgs', max_iter=1000)
model.fit(features_train_n, target_train)

probabilities = model.predict_proba(features_valid)

probabilities_one_valid = [i[1] for i in probabilities] # оставляем только положительную вероятность

t = 0
f = 0

for threshold in np.arange(0, 1, 0.02): # ГРАНИЦЫ ПОРОГА
    predicted_valid = probabilities_one_valid > threshold # булев массив с разными значениями порога
    f1 = f1_score(target_valid, predicted_valid)
    if(f1 > f):
        f = f1
        t = threshold

print(t, f)

0.52 0.7317073170731707

порог не меняем, так как он почти равен обычному 0.5

проверка на вменяемость

In [1123]:
f1 = f1_score(target_valid, [0 for i in range(0, len(target_valid))])
f1

0.0

In [1124]:
f1 = f1_score(target_valid, [1 for i in range(0, len(target_valid))])
f1

0.5388726701100383

In [1125]:
features_test = pd.DataFrame(data=scaler.transform(features_test), columns=features.columns)

In [1126]:
model = LogisticRegression(random_state=12345, class_weight='balanced', solver='lbfgs', max_iter=1000)
model.fit(features, target)
predict = model.predict(features_test)
print(f1_score(target_test, predict))
print(f1_score(target_test, [1 for i in range(0, len(target_test))]))
print(f1_score(target_test, [0 for i in range(0, len(target_test))]))

0.6769811320754717
0.5594281005723448
0.0

In [1127]:
def profit_predict(target_predict, features):
    count = 0
    for i in range(len(features)):
        if(features.loc[i]['is_canceled'] == 1 and target_predict[i] == 1):
            count += features.iloc[i].profit_one_order * 0.2
        else:
            count += features.iloc[i].profit_one_order
    return count

In [1137]:
income_with_deposite = profit_predict(predict, df_test.reset_index(drop=True))
print('incom_with_model', income_with_deposite)
print('incom_without_model', income_without_deposite)
print('разница', income_with_deposite - income_without_deposite)

incom_with_model 41345898.0
incom_without_model 28196210.0
разница 13149688.0

### Шаг 5. Опишите портрет «ненадёжного» клиента

### Шаг 6. Напишите общий вывод